plugin: aws_ec2
regions:
  - us-east-1
keyed_groups:
  - prefix: tag
    key: tags
filters:
  tag:Project: nginx
  instance-state-name: running
hostnames:
  - private-ip-address
compose:
  ansible_host: private_ip_address
