plugin: aws_ec2
regions:
  - us-east-1    # your AWS region here
keyed_groups:
  - key: tags.NGINX_Private
    prefix: tag_NGINX_Private
    separator: "_"
filters:
  "tag:Project": "nginx"
hostnames:
  - tag:Name
compose:
  ansible_host: public_ip_address

