---
plugin: aws_ec2

# AWS region to query
regions:
  - us-east-1

# Filter EC2 instances by tag Role=NGINX-Private
filters:
  tag:Role: NGINX-Private
  instance-state-name: running

# Use private IP address to connect (since instance is private)
hostnames:
  - private-ip-address

# Group hosts by tag Role and Name (optional)
keyed_groups:
  - key: tags.Role
    prefix: tag_Role_
  - key: tags.Name
    prefix: tag_Name_
