plugin: amazon.aws.aws_ec2
regions:
  - us-east-1

filters:
  tag:Type: webserver  # Or match based on your EC2 tag

hostnames:
  - private-ip-address

compose:
  ansible_user: ec2-user
  ansible_ssh_private_key_file: "<private_key_path>"

keyed_groups:
  - key: tags.Name
    prefix: ""

