plugin: aws_ec2
regions:
  - us-east-1        # Change this to your AWS region
filters:
  "tag:Name": "NGINX-Private"   # Filter EC2 instances by tag Name=NGINX-Private
keyed_groups:
  - key: tags.Name
    prefix: tag
hostnames:
  - tag:Name
