plugin: amazon.aws.aws_ec2
regions:
  - us-east-1

filters:
  tag:NGINX_Private: "yes"

keyed_groups:
  - key: tags.Name
    prefix: tag_Name_
  - key: tags.Project
    prefix: tag_Project_
  - key: tags.NGINX_Private
    prefix: tag_NGINX_Private_

hostnames:
  - private-ip-address  # Private IP for use with Bastion jump

compose:
  ansible_host: private_ip_address

strict: false
