plugin: aws_ec2
regions:
  - us-east-1
filters:
  tag:Project: nginx
keyed_groups:
  - key: tags
    prefix: tag
    separator: _
hostnames:
  - private-ip-address
compose:
  ansible_host: private_ip_address
