- name: Install NGINX on private EC2 via Bastion
  hosts: tag_NGINX_Private_yes
  gather_facts: yes

  tasks:
    - name: Install nginx
      ansible.builtin.yum:
        name: nginx
        state: present
      become: yes

    - name: Start and enable nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
      become: yes
