- name: Install NGINX on private EC2 via Bastion
  hosts: all
  become: true
  remote_user: ubuntu
  gather_facts: yes

  tasks:
    - name: Install nginx (only on Debian-based systems)
      apt:
        name: nginx
        state: present
        update_cache: yes
      when: ansible_facts.os_family == "Debian"

    - name: Start and enable nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true

