- name: Install NGINX on private EC2 via Bastion
  hosts: all #tag_NGINX_Private_yes
  gather_facts: yes

  tasks:
  - name: Install nginx
    apt:
      name: nginx
      state: present
      update_cache: yes
    when: ansible_facts.os_family == "Debian"


    - name: Start and enable nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
      become: yes
